### ISSUE TITLE
Unable to Use JSON Schema

### ISSUE THREAD

**Issue by sbryfcz** [ngstack/code-editor#1015]
I was hoping to see what type of JSON schema support is included. However whenever I add a `schemas` list as shown in the documentation I receive a runtime error of:

```
core.mjs:6494 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'languages')
TypeError: Cannot read properties of undefined (reading 'languages')
    at JsonDefaultsService.addSchemas (ngstack-code-editor.mjs:311:38)
    at CodeEditorComponent.setupDependencies (ngstack-code-editor.mjs:465:43)
    at CodeEditorComponent.setupEditor (ngstack-code-editor.mjs:443:14)
    at CodeEditorComponent.<anonymous> (ngstack-code-editor.mjs:422:18)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76:1
    at new ZoneAwarePromise (zone.js:1429:1)
    at __awaiter (tslib.es6.js:72:1)
    at CodeEditorComponent.ngAfterViewInit (ngstack-code-editor.mjs:421:25)
    at callHook (core.mjs:2551:1)
    at resolvePromise (zone.js:1211:1)
    at new ZoneAwarePromise (zone.js:1432:1)
    at __awaiter (tslib.es6.js:72:1)
    at CodeEditorComponent.ngAfterViewInit (ngstack-code-editor.mjs:421:25)
    at callHook (core.mjs:2551:1)
    at callHooks (core.mjs:2520:1)
    at executeInitAndCheckHooks (core.mjs:2471:1)
    at refreshView (core.mjs:9566:1)
    at refreshComponent (core.mjs:10692:1)
    at refreshChildComponents (core.mjs:9291:1)
```

Going a level deeper, it looks like this.monaco is undefined:

```
addSchemas(id, definitions = []) {
        const defaults = this.monaco.languages.json.jsonDefaults;
        ....
```

Anyone have advice?

**Comment by giovanni-bertoncelli** [comment]
I think `this.monaco` does not exists. Will PR

**Comment by giovanni-bertoncelli** [comment]
Same issue with version 4.0.0 (since using angular 13)... @DenysVuika any insights for this?

**Comment by Marcus-Goectau** [comment]
Still having this same issue on version 5.0.0. Used to work on version.

**Comment by DenysVuika** [comment]
I have it working in the default demo, you can check the code here: https://github.com/ngstack/code-editor/blob/d930ad4ddf18fcaf313432d3772b520849d38a18/src/app/code-editor-demo/file-database.ts#L56

**Comment by fMoro1999** [comment]
Hi,

it seems the problem persists. Currently my team uses 5.0.0 version. The error is the same of OP. Tried also with offline version.
