### ISSUE TITLE
ReferenceError: monaco is not defined

### ISSUE THREAD

**Issue by towify** [ngstack/code-editor#1037]
angular 14, when i run the application get error 

main.js:326591 ERROR Error: Uncaught (in promise): ReferenceError: monaco is not defined
ReferenceError: monaco is not defined
    at CodeEditorComponent.setupEditor (907.js:3127:19)
    at CodeEditorComponent.<anonymous> (907.js:3116:12)
    at Generator.next (<anonymous>)
    at main.js:259177:71
    at new ZoneAwarePromise (polyfills.js:6619:23)
    at __awaiter (main.js:259173:12)
    at CodeEditorComponent.ngAfterViewInit (907.js:3115:60)
    at callHook (main.js:321621:14)
    at callHooks (main.js:321594:9)
    at executeInitAndCheckHooks (main.js:321551:5)
    at resolvePromise (polyfills.js:6538:21)
    at new ZoneAwarePromise (polyfills.js:6621:11)
    at __awaiter (main.js:259173:12)
    at CodeEditorComponent.ngAfterViewInit (907.js:3115:60)
    at callHook (main.js:321621:14)
    at callHooks (main.js:321594:9)
    at executeInitAndCheckHooks (main.js:321551:5)
    at refreshView (main.js:330899:11)
    at refreshComponent (main.js:331937:7)
    at refreshChildComponents (main.js:330627:5)

**Comment by DenysVuika** [comment]
the latest supported version of Angular is 13, support for Angular 15 is coming soon

**Comment by dsuwirya-cloudwiz** [comment]
@DenysVuika,

I'm using v5.0.0 which is supposedly supporting Angular 15, and I'm still getting this error.

Can you please give guidance on how to resolve this?

Thanks.
