### ISSUE TITLE
Cannot find module 'monaco-editor'

### ISSUE THREAD

**Issue by felix-adhinata** [ngstack/code-editor#1343]
I am upgrading this in my project from v5.1.0 (ng16) to v7.2.0 (ng17) and then I got this error when running my test.

```
Error: node_modules/@ngstack/code-editor/lib/code-editor/code-editor.component.d.ts:7:24 - error TS2307: Cannot find module 'monaco-editor' or its corresponding type declarations.

7 import { editor } from 'monaco-editor';
                         ~~~~~~~~~~~~~~~


Error: node_modules/@ngstack/code-editor/lib/services/code-editor.service.d.ts:4:24 - error TS2307: Cannot find module 'monaco-editor' or its corresponding type declarations.

4 import { editor } from 'monaco-editor';
```

I am not installing `monaco-editor` on my package.json since I don't need offline mode in my project.

Will install v7.1.0 for now since it seems the imports are added on v7.2.0, but I hope this can be resolved in a future version.

**Comment by natebjensen** [comment]
I am having the same issue

**Comment by cathey191** [comment]
Also run into this issue.

**Comment by tipodisimmia** [comment]
Same issue with:
    "@angular/compiler": "^14.2.12",
    "@ngstack/code-editor": "^4.0.0"
Runtime log show:
Error: Uncaught (in promise): ReferenceError: monaco is not defined
ReferenceError: monaco is not defined
    at CodeEditorComponent.setupEditor (ngstack-code-editor.mjs:433:23)
    at ngstack-code-editor.mjs:422:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1340:33)
    at asyncToGenerator.js:21:1
    at CodeEditorComponent.ngAfterViewInit (ngstack-code-editor.mjs:421:29)
    at callHook (core.mjs:2498:22)
    at resolvePromise (zone.js:1255:35)
    at zone.js:1162:21
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1340:33)
    at asyncToGenerator.js:21:1
    at CodeEditorComponent.ngAfterViewInit (ngstack-code-editor.mjs:421:29)
    at callHook (core.mjs:2498:22)
    at callHooks (core.mjs:2467:17)
    
    And the content of editor is an empty div.....

**Comment by DenysVuika** [comment]
The repository comes with example applications. Please check if it's running for you and application configuration, if you have issues.

**Comment by felix-adhinata** [comment]
the example application has `"monaco-editor": "^0.50.0",` as dependencies, that make it work. I don't want to add that dependency to my project configuration.

**Comment by DenysVuika** [comment]
@felix-adhinata this component is a thin wrapper for the monaco-editor library, as pretty much any other monaco-based editor component out there. If you want a component without monaco dependency, check out other component libraries

**Comment by felix-adhinata** [comment]
thanks for the clarification @DenysVuika
